### ISSUE TITLE
No (channel) parameters in programming board after applying the script

### ISSUE THREAD

**Issue by 3kynox** [PerMalmberg/du-yfs-gate-control#1]
Hello Yoarii, I know you're retired from DU but I wanted to ask anyway if you have a clue why when I'm applying the gate json script to a programming board (with all the correct links done before) I'm seeing no code inside the PB and there's no lua parameter at all to edit (returns `lua script has no exported variables`). Elevator works smoothly well on a MyDU server btw.

Thanks in advance, according to your time.

**Comment by PerMalmberg** [comment]
I'd guess you're pasting more than the Json file. Does it say Lua was successfully applied? (I think it is meant to do that, right?)

**Comment by 3kynox** [comment]
Indeed, there was maybe an extra space at the end accounted by my text editor. Tried to copy it properly and I can now select the commChan on the pb. Now struggling with doors being on the opposite side of what they should be. But that should be manageable.

I'm planning to take the follow-up of your scripts in the future until I find how to compile the scripts (looks like there is Makefiles included in your projects). This MyDU initiative from NQ looks like to motivate many peoples and that's a lot of fun. I'm a confirmed programmer but less confirmed in the DU lua side of things.

Thanks again for your fast answer.

**Comment by PerMalmberg** [comment]
Cool, glad it works now.
